import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {newConversation,advanceConversation as advance,conversationView as view,modelContext,relevantRecords} from '../src/conversation-model.js';
import {handleApi} from '../server/api.js';
import {interpretConversation} from '../server/conversation-ai.js';
const act=(s,action,extra={})=>advance(s,{action,...extra});const say=(s,value,context={})=>advance(s,{value},context);
function captured(){let s=act(newConversation(),'reflect');s=say(s,'A presentation tomorrow');s=say(s,'I might freeze during my presentation');return act(s,'confirm');}
function branch(type){return act(captured(),type);}
function finishWork(s,value='My own words'){let guard=0;while(s.state==='WORK'&&guard++<30)s=say(s,view(s).type==='slider'?70:value);return s;}
test('ready immediately: user choice overrides overwhelmed inference, no forced stabilization',()=>{let s=say(newConversation(),'I cannot think');assert.equal(s.state,'READINESS');s=advance(s,{action:'reflect'},{model:{readiness:'overwhelmed'}});assert.equal(s.field,'worry');assert.deepEqual(s.tried,[]);});
test('overwhelmed or uncertain: asks preference without diagnosing panic',()=>{for(const message of ['I cannot think','I am freaking out','My mind won’t stop','I can’t focus']){const s=say(newConversation(),message);assert.equal(s.state,'READINESS');assert.ok(!view(s).message.toLowerCase().includes('panic'));assert.equal(act(s,'settle').state,'SETTLE');}});
test('breathing declined: different modality and no future breathing offer after restart',()=>{let s=act(act(newConversation(),'settle'),'physical');s=act(s,'breathing');s=say(s,'Breathing makes it worse');assert.ok(s.declined.includes('breathing'));assert.notEqual(s.intervention,'breathing');s=act(s,'restart');s=act(act(s,'settle'),'physical');assert.ok(!view(s).choices.some(c=>c.id==='breathing'));});
test('breathing not helping and grounding not helping do not repeat instructions',()=>{for(const id of ['breathing','grounding']){let s={...newConversation(),state:'STABILIZE',intervention:id,tried:[id]};s=say(s,'This is not helping');assert.equal(s.state,'SETTLE');assert.ok(s.declined.includes(id));if(id==='grounding'){s=act(s,'around');assert.notEqual(s.intervention,'grounding');}}});
test('one-word no changes stabilization approach; stay is voluntary and no score gate exists',()=>{let s={...newConversation(),state:'STABILIZE',intervention:'grounding',tried:['grounding']};assert.equal(say(s,'No').state,'SETTLE');s=say(s,'I can feel the floor');assert.equal(s.state,'READY');s.answers.initialDistress=100;assert.equal(act(s,'reflect').field,'worry');});
test('restart, pause, go back and end remain available with saved place',()=>{let s=captured();s=act(s,'pause');assert.equal(s.state,'PAUSED');assert.equal(act(s,'resume').field,'actionability');assert.equal(say(s,'start over').state,'READINESS');s=act(s,'end');assert.equal(s.state,'ENDED');});
test('vague worry receives at most two extra clarification questions and editable confirmation',()=>{let s=act(newConversation(),'reflect');s=say(s,'Tomorrow');assert.equal(s.field,'prediction');s=say(s,'Dunno');s=say(s,'Not sure');assert.equal(s.clarifications,2);s=say(s,'Tomorrow');assert.equal(s.state,'CONFIRM');s=act(s,'confirm',{prediction:'Something uncertain might happen tomorrow'});assert.equal(s.answers.prediction,'Something uncertain might happen tomorrow');});
test('practical problem takes bounded planning path without probability questions',()=>{const s=finishWork(branch('Something I can act on'));assert.equal(s.state,'REMAINING');const final=act(s,'finishPlan');assert.equal(final.state,'SUMMARY');assert.equal(final.answers.initialProbability,undefined);});
test('mixed worry offers uncertain branch after practical action',()=>{const s=act(finishWork(branch('Both')),'explore');assert.equal(s.field,'initialProbability');});
test('hypothetical worry separates likelihood and distress and offers minimum useful focus',()=>{let s=branch('An uncertain prediction');s=say(s,90);s=say(s,40);s=say(s,'Losing my place');assert.equal(s.state,'FOCUS');assert.equal(s.answers.initialProbability,90);assert.equal(s.answers.initialDistress,40);assert.equal(act(s,'brief').field,'realisticScenario');assert.equal(act(s,'evidence').field,'evidenceFor');});
test('unchanged and increasing estimates remain intact, including genuinely likely outcomes',()=>{for(const revised of [90,99]){let s=finishWork(branch('An uncertain prediction'));s=act(s,'brief');s=say(s,'It may genuinely happen; I can bring notes.');s=say(s,revised);assert.equal(s.state,'UNCERTAINTY');assert.equal(s.answers.revisedProbability,revised);assert.ok(!/great|well done|better/i.test(view(s).message));}});
test('no evidence against is accepted, without fabricated counter-evidence',()=>{let s=act(finishWork(branch('An uncertain prediction')),'evidence');s=say(s,'I have very little preparation time');s=say(s,'Nothing comes to mind');assert.equal(s.answers.evidenceAgainst,'Nothing comes to mind');assert.equal(s.field,'initialSeverity');});
test('repeated prediction offers reflection/change/attention instead of restarting analysis',()=>{let s=act(newConversation(),'reflect');s=say(s,'Presentation tomorrow');s=say(s,'I might freeze during my presentation');const prior={id:'old',status:'complete',answers:{worry:'Presentation',prediction:'I might freeze during my presentation',realisticScenario:'I can use notes'},outcome:{result:'Did not happen'}};s=advance(s,{action:'confirm'},{records:[prior]});assert.equal(s.state,'REPEAT');assert.equal(act(s,'reviewPrevious').state,'PREVIOUS');assert.equal(act(s,'changed').state,'CHANGE');assert.equal(act(s,'shift').intervention,'attention');});
test('history uses only supplied verified records selected by the patient',()=>{let s=branch('An uncertain prediction');const r={id:'past',status:'complete',answers:{prediction:'A presentation may go badly',worry:'presentation'},outcome:{result:'Did not happen'}};assert.deepEqual(relevantRecords([],r.answers.prediction),[]);s.history=[{id:r.id,prediction:r.answers.prediction,outcome:r.outcome}];s.state='HISTORY';s=act(s,'useHistory',{ids:['past','invented']});assert.deepEqual(s.relatedIds,['past']);assert.equal(modelContext(s,'hello').previousRelevantOutcomes[0].result,'Did not happen');});
test('no history skips history inquiry, unresolvable uncertainty can end with no review date',()=>{let s=act(finishWork(branch('An uncertain prediction')),'brief');s=finishWork(s);s=say(s,'I cannot know for sure, but can take the next step');s=act(s,'leaveRatings');s=act(s,'notTestable');assert.equal(s.state,'SUMMARY');assert.equal(s.outcomeDueAt,null);});
test('already supplied details require confirmation, then are not asked again',()=>{let s=branch('Something I can act on');s=say(s,'I can prepare notes tomorrow',{model:{extractedData:{nextStep:'prepare notes',actionWhen:'tomorrow'}}});assert.equal(s.state,'DETAILS');assert.equal(s.answers.nextStep,undefined);s=act(s,'acceptDetails');assert.equal(s.answers.nextStep,'prepare notes');s=say(s,'prepare notes or rehearse');assert.equal(s.state,'REMAINING');});
test('outcome review stores due time, actual difficulty, coping and learning without changing prediction',()=>{let s={...captured(),state:'REVIEW_AT',answers:{...captured().answers,testable:'Yes',initialSeverity:90}};s=say(s,'2026-10-02T18:00:00Z');assert.equal(s.outcomeDueAt,'2026-10-02T18:00:00.000Z');s=act(s,'complete');s=act(s,'reviewOutcome');s=act(s,'Partly happened');s=say(s,60);s=say(s,'I used my notes');s=say(s,'Pausing did not stop the presentation');assert.equal(s.state,'COMPLETE');assert.equal(s.answers.initialSeverity,90);assert.equal(s.outcome.actualSeverity,60);assert.equal(s.outcome.copingDescription,'I used my notes');});
test('safety interrupts reflection and still allows ending without ordinary disputation',()=>{let s=say(branch('An uncertain prediction'),'I cannot stay safe');assert.equal(s.state,'SAFETY');s=act(s,'end');assert.equal(s.state,'ENDED');s=act(s,'resume');assert.equal(s.state,'SAFETY');assert.equal(act(s,'reflect').state,'SAFETY');});
test('minimal model context excludes unselected records, raw audio metadata and full transcript',()=>{const s=captured();s.voice=[{rawTranscript:'private'}];s.history=[{id:'unselected',prediction:'private'}];s.transcript=Array.from({length:40},(_,i)=>({role:'user',text:'turn '+i}));const c=modelContext(s,'last');assert.equal(c.previousRelevantOutcomes.length,0);assert.equal(c.currentConversationSummary.lastExchange.length,2);assert.equal(c.voice,undefined);});
test('clarification question does not become clinical evidence or advance the step',()=>{let s=act(finishWork(branch('An uncertain prediction')),'evidence');s=say(s,'What do you mean by evidence?');assert.equal(s.field,'evidenceFor');assert.equal(s.answers.evidenceFor,undefined);assert.match(s.aiMessage,/actually noticed/);});
test('pause clears stale AI wording and repeating with no new information returns to reflection choices',()=>{let s={...captured(),aiMessage:'A previous question'};s=act(s,'pause');assert.equal(s.aiMessage,null);s.state='CHANGE';s=say(s,'Nothing new');assert.equal(s.state,'REPEAT');assert.equal(act(s,'reflect').state,'REPEAT');});
test('back does not resurrect declined breathing and edited predictions pass safety routing',()=>{let s=act(act(act(newConversation(),'settle'),'physical'),'breathing');s=say(s,'Breathing makes it worse');s=act(s,'back');assert.notEqual(s.state==='STABILIZE'&&s.intervention,'breathing');s.state='CONFIRM';s=act(s,'confirm',{prediction:'I might kill myself'});assert.equal(s.state,'SAFETY');});
function db(){const d=new DatabaseSync(':memory:');d.exec(readFileSync(new URL('../drizzle/0000_robust_silhouette.sql',import.meta.url),'utf8'));return {prepare(sql){return {bind(...v){const st=d.prepare(sql);return {async all(){return {results:st.all(...v)};},async first(){return st.get(...v)||null;},async run(){return {meta:{changes:Number(st.run(...v).changes)}};}};}};}};}
const client=(env,owner='a')=>async(path,body)=>{const r=await handleApi(new Request('https://test.local/api/'+path,{method:body===undefined?'GET':'POST',headers:{Origin:'https://test.local','oai-authenticated-user-id':owner},body:body===undefined?undefined:JSON.stringify(body)}),env);return {status:r.status,...await r.json()};};
test('leaving halfway persists draft/state and owner/revision checks prevent leakage or overwrite',async()=>{const env={DB:db()},a=client(env),b=client(env,'b');let {session:s}=await a('conversations',{});s=(await a(`conversations/${s.id}/turn`,{revision:s.revision,action:'reflect'})).session;const revision=s.revision;await a(`conversations/${s.id}/draft`,{revision,text:'unfinished exact words'});const restored=await a('conversations/'+s.id);assert.equal(restored.session.draftText,'unfinished exact words');assert.equal(restored.session.field,'worry');assert.equal((await b('conversations/'+s.id)).status,404);assert.equal((await a(`conversations/${s.id}/draft`,{revision,text:'stale'})).status,409);assert.equal((await a('worries/'+s.id)).status,404);});
test('voice transcript keeps raw/cleaned/approved separately and rejects unapproved mutation',async()=>{const a=client({DB:db()});let {session:s}=await a('conversations',{});s=(await a(`conversations/${s.id}/turn`,{revision:s.revision,action:'reflect'})).session;const path=`conversations/${s.id}/turn`;const wrong=await a(path,{revision:s.revision,value:'Presentation.',voice:{rawTranscript:'presentation',cleanedTranscript:null,patientApprovedText:'wrong'}});assert.equal(wrong.status,400);const saved=await a(path,{revision:s.revision,value:'Presentation.',voice:{rawTranscript:'presentation',cleanedTranscript:null,patientApprovedText:'Presentation.'}});assert.equal(saved.session.voice[0].rawTranscript,'presentation');assert.equal(saved.session.voice[0].patientApprovedText,'Presentation.');});
test('approved practical reflection is mirrored into existing worry records once',async()=>{const a=client({DB:db()});let {session:s}=await a('conversations',{});const turn=async event=>{const r=await a(`conversations/${s.id}/turn`,{revision:s.revision,...event});assert.equal(r.status,200);s=r.session;};await turn({action:'reflect'});await turn({value:'Finish my slides tomorrow'});await turn({value:'I might not finish my slides'});await turn({action:'confirm'});await turn({action:'Something I can act on'});for(const value of ['My preparation','Rehearse or make notes','Make notes','Tonight'])await turn({value});await turn({action:'finishPlan'});await turn({action:'complete'});const list=await a('worries');assert.equal(list.records.length,1);assert.equal(list.records[0].answers.nextStep,'Make notes');assert.equal(list.records[0].conversationId,s.id);assert.equal(list.records[0].status,'complete');assert.equal((await a(`conversations/${s.id}/turn`,{revision:s.revision,action:'complete'})).status,400);});
test('model cannot inject a transition or fabricated controls',async()=>{const s=newConversation();const planned=act(s,'reflect');const invalid={assistantMessage:'Do this',conversationAction:'ASK',suggestedState:'COMPLETE',extractedData:{prediction:'',evidenceFor:'',evidenceAgainst:'',coping:'',nextStep:'',actionWhen:''},ui:{type:'text',options:[]},reason:'test',requiresConfirmation:false,readiness:'uncertain',interventionFeedback:'neutral'};await assert.rejects(()=>interpretConversation({GROQ_API_KEY:'test'},s,'hello',planned,async()=>Response.json({choices:[{finish_reason:'stop',message:{content:JSON.stringify(invalid)}}]})),/Invalid proposed transition/);});
