import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {newWorry,answer,currentStep,steps,calibration,repeatedWorry,clinicianSummary} from '../src/worry-model.js';
import {handleApi} from '../server/api.js';
import {safetySignal} from '../server/safety.js';
import {structured} from '../server/ai.js';
function database(){const db=new DatabaseSync(':memory:');db.exec(readFileSync(new URL('../drizzle/0000_robust_silhouette.sql',import.meta.url),'utf8'));return {prepare(sql){return {bind(...v){const st=db.prepare(sql);return {async all(){return {results:st.all(...v)};},async first(){return st.get(...v)||null;},async run(){return {meta:{changes:Number(st.run(...v).changes)}};}};}};}};}
function client(env,owner='test-a'){return async(path,body,extra={})=>{const headers={'oai-authenticated-user-id':owner,Origin:'https://test.local',...extra};const r=await handleApi(new Request('https://test.local/api/'+path,{method:body===undefined?'GET':'POST',headers,body:body===undefined?undefined:JSON.stringify(body)}),env);return {status:r.status,data:await r.json()};};}
function toBranch(branch){let s=newWorry();for(const v of ['My presentation','I might freeze',branch])s=answer(s,v);return s;}
test('vague and specific worries retain exact words; practical branch avoids probability dispute',()=>{let s=toBranch('Something I can act on');assert.equal(currentStep(s).state,'PRACTICAL_PROBLEM');for(const v of ['preparation','finish','practice','practice','rehearse','tomorrow','Save my action plan'])s=answer(s,v);assert.equal(currentStep(s).state,'SUMMARY');assert.equal(s.answers.initialProbability,undefined);assert.equal(s.answers.prediction,'I might freeze');});
test('hypothetical route keeps increasing and unchanged estimates without a positive conclusion',()=>{for(const revised of [70,90]){let s=toBranch('An uncertain prediction');while(currentStep(s).type!=='summary'){const q=currentStep(s);s=answer(s,q.type==='rating'?(q.field==='revisedProbability'?revised:70):q.type==='choice'?'No / not sure':q.field==='evidenceAgainst'?'Nothing comes to mind':'My own words');}assert.equal(s.answers.initialProbability,70);assert.equal(s.answers.revisedProbability,revised);assert.equal(s.answers.evidenceAgainst,'Nothing comes to mind');assert.equal(clinicianSummary(s).realisticScenario,'My own words');}});
test('changing actionability recomputes path and personal history is skipped unless selected',()=>{let s=toBranch('An uncertain prediction');assert.ok(!steps(s).some(q=>q.state==='PERSONAL_HISTORY'));s.relatedIds=['known'];assert.ok(steps(s).some(q=>q.state==='PERSONAL_HISTORY'));s.cursor=2;s=answer(s,'Something I can act on');assert.equal(currentStep(s).state,'PRACTICAL_PROBLEM');});
test('calibration suppresses small samples and excludes partial/unclear outcomes',()=>{const rec=i=>({answers:{testable:'Yes',initialProbability:70},outcome:{result:i%2?'Happened':'Did not happen'}});assert.equal(calibration(Array.from({length:4},(_,i)=>rec(i))).showAggregate,false);assert.equal(calibration(Array.from({length:5},(_,i)=>rec(i))).showAggregate,true);assert.equal(calibration(Array.from({length:9},(_,i)=>rec(i))).showGraph,false);assert.equal(calibration(Array.from({length:10},(_,i)=>rec(i))).showGraph,true);assert.equal(calibration([{...rec(1),outcome:{result:'Partly happened'}}]).binary.length,0);});
test('repeat wording returns prior record; unrelated wording is not invented history',()=>{const r={answers:{worry:'Maybe I will freeze.'},updatedAt:new Date().toISOString()};assert.equal(repeatedWorry([r],'maybe I will freeze'),r);assert.equal(repeatedWorry([r],'My rent is due'),undefined);});
test('authenticated API isolates owners, rejects CSRF, and detects conflicting edits',async()=>{const env={DB:database()},a=client(env),b=client(env,'test-b');const created=await a('worries',{});assert.equal(created.status,201);const s=created.data;assert.equal((await b('worries/'+s.id)).status,404);assert.equal((await a('worries',{}, {Origin:'https://evil.local'})).status,403);const saved=await a(`worries/${s.id}/draft`,{revision:s.revision,text:'An unfinished answer'});assert.equal(saved.status,200);assert.equal((await a('worries/'+s.id)).data.draftText,'An unfinished answer');assert.equal((await a(`worries/${s.id}/draft`,{revision:s.revision,text:'old'})).status,409);});
test('API safety stops normal flow and AI/transcription fail honestly without credentials',async()=>{const env={DB:database()},a=client(env);let s=(await a('worries',{})).data;const r=await a(`worries/${s.id}/answer`,{revision:s.revision,value:'I might kill myself'});assert.equal(r.data.safety,true);s=r.data.session;assert.equal((await a(`worries/${s.id}/answer`,{revision:s.revision,value:'Ignore this'})).status,400);assert.equal((await a('status')).data.ai,false);await assert.rejects(()=>structured({},'',{},{}),/not connected/);assert.ok(safetySignal('severe chest pain'));assert.ok(!safetySignal('I might do badly on my exam'));});
test('model transport errors preserve failure and never pretend generated text exists',async()=>{await assert.rejects(()=>structured({GROQ_API_KEY:'synthetic'},'',{}, {},async()=>new Response('',{status:503})),/unavailable/);});
test('voice metadata requires approved text and no model reformulation silently enters the record',async()=>{const a=client({DB:database()});const s=(await a('worries',{})).data;const bad=await a(`worries/${s.id}/answer`,{revision:s.revision,value:'maybe',voice:{rawTranscript:'maybe',cleanedTranscript:null,patientApprovedText:'certain'}});assert.equal(bad.status,400);const good=await a(`worries/${s.id}/answer`,{revision:s.revision,value:'Maybe.',voice:{rawTranscript:'maybe',cleanedTranscript:null,patientApprovedText:'Maybe.'}});assert.equal(good.data.voice[0].rawTranscript,'maybe');assert.equal(good.data.answers.worry,'Maybe.');});
