import {createServer} from 'node:http';
import {readFile,readdir,mkdir} from 'node:fs/promises';
import {DatabaseSync} from 'node:sqlite';
import {loadEnvFile} from 'node:process';
try { loadEnvFile('.env.local'); } catch (error) { if(error.code!=='ENOENT') throw error; }
import {handleApi} from '../server/api.js';
await mkdir(new URL('../work/',import.meta.url),{recursive:true});
const sqlite=new DatabaseSync(new URL('../work/preview.sqlite',import.meta.url));
sqlite.exec('CREATE TABLE IF NOT EXISTS local_migrations (name TEXT PRIMARY KEY)');
for(const file of (await readdir(new URL('../drizzle/',import.meta.url))).filter(f=>f.endsWith('.sql')).sort())if(!sqlite.prepare('SELECT name FROM local_migrations WHERE name=?').get(file)){sqlite.exec(await readFile(new URL('../drizzle/'+file,import.meta.url),'utf8'));sqlite.prepare('INSERT INTO local_migrations(name) VALUES (?)').run(file);}
const db={prepare(sql){return {bind(...values){const stmt=sqlite.prepare(sql);return {async all(){return {results:stmt.all(...values)};},async first(){return stmt.get(...values)||null;},async run(){const r=stmt.run(...values);return {meta:{changes:Number(r.changes)}};}};}};}};
const port=Number(process.env.PORT||4173);
const allowed=new Set(await readdir(new URL('../src/',import.meta.url)));
createServer(async(req,res)=>{try{const origin='http://127.0.0.1:'+port,url=new URL(req.url,origin);if(url.pathname.startsWith('/api/')){const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>9*1024*1024){res.writeHead(413).end();return;}chunks.push(chunk);}const headers=new Headers(req.headers);headers.set('oai-authenticated-user-id','local-synthetic-preview');const request=new Request(url,{method:req.method,headers,body:['GET','HEAD'].includes(req.method)?undefined:Buffer.concat(chunks)});const response=await handleApi(request,{DB:db,...Object.fromEntries(Object.entries(process.env).filter(([key])=>key.startsWith('PAASAA_'))),GROQ_API_KEY:process.env.GROQ_API_KEY,GROQ_MODEL:process.env.GROQ_MODEL,GROQ_TEXT_MODEL:process.env.GROQ_TEXT_MODEL,GROQ_TRANSCRIPTION_MODEL:process.env.GROQ_TRANSCRIPTION_MODEL});res.writeHead(response.status,Object.fromEntries(response.headers));res.end(Buffer.from(await response.arrayBuffer()));return;}const name=url.pathname==='/'?'index.html':url.pathname.slice(1);if(!allowed.has(name)){res.writeHead(404).end();return;}res.writeHead(200,{'Content-Type':name.endsWith('.html')?'text/html':name.endsWith('.css')?'text/css':name.endsWith('.svg')?'image/svg+xml':'text/javascript','Cache-Control':'no-store'});res.end(await readFile(new URL('../src/'+name,import.meta.url)));}catch{res.writeHead(500).end('Preview unavailable');}}).listen(port,'127.0.0.1',()=>console.log('Paasaa preview: http://127.0.0.1:'+port+' — synthetic local account only'));
