import {requireAccount} from './auth.js';
import {apiFetch} from './api-client.js';
import {newConversation,conversationView,fields} from './conversation-model.js';
import {mountChatExercise} from './chat-exercise.js';
import {createChatVoice} from './chat-voice.js';
import {localChatContext} from './chat-context.js';
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const button=(text,fn,cls='')=>{const b=el('button',text,cls);b.type='button';b.onclick=fn;return b;};
const api=async(path,body)=>{const r=await apiFetch('/api/'+path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});let d;try{d=await r.json();}catch{throw Error('The connection is unavailable. Your words remain here.');}if(!r.ok)throw Error(d.error||'Could not save. Your words remain here.');return d;};
const display=v=>v===null||v===undefined||v===''?'Not answered':String(v);

function icon(name){
  const paths={mic:'M12 3a3 3 0 0 0-3 3v6a3 3 0 0 0 6 0V6a3 3 0 0 0-3-3 M5 10v2a7 7 0 0 0 14 0v-2 M12 19v3 M8 22h8',send:'m3 3 18 9-18 9 4-9-4-9 M7 12h14',more:'M5 12h.01 M12 12h.01 M19 12h.01',stop:'M6 6h12v12H6z'};
  const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('width','22');svg.setAttribute('height','22');svg.setAttribute('fill','none');svg.setAttribute('stroke','currentColor');svg.setAttribute('stroke-width',name==='more'?'3':'1.8');svg.setAttribute('stroke-linecap','round');svg.setAttribute('stroke-linejoin','round');svg.setAttribute('aria-hidden','true');const path=document.createElementNS(svg.namespaceURI,'path');path.setAttribute('d',paths[name]);svg.append(path);return svg;
}

export function createChat(_checkin,openSafety){
  const root=document.getElementById('chat-screen');let session=newConversation(true,true),persisted=false,available=false,loaded=false,active=false,busy=false,records=[],dirty=false,localDraft='',generation=0,timer,queue=Promise.resolve(),exerciseCleanup=()=>{},voiceCleanup=()=>{},voice=null,statusNode,composer,sliderValue=null,predictionInput,detailsInputs={},historyInputs=[],pendingAction=null;
  const status=message=>{if(statusNode)statusNode.textContent=message;};
  function setBusy(value){busy=value;root.setAttribute('aria-busy',String(value));root.querySelectorAll('input,textarea,select,button[data-turn],button[data-edit]').forEach(n=>n.disabled=value||n.dataset.requiresAi==='true'&&!available);}
  async function ensure(){if(!persisted){const r=await api('conversations',{aiConsent:session.aiConsent,companion:session.companion});session=r.session;persisted=true;}}
  function mutate(op,body){const run=queue.catch(()=>{}).then(async()=>{await ensure();const r=await api(`conversations/${session.id}/${op}`,{...body,revision:session.revision});session=r.session;records=[{id:session.id,state:session.state,companion:!!session.companion,title:session.answers.worry||session.openingMessage||'A moment for yourself',status:session.status,outcomeDueAt:session.outcomeDueAt,outcome:session.outcome},...records.filter(x=>x.id!==session.id)];return r;});queue=run;return run;}
  function saveDraft(value){if(session.companion){session.draftText=value;status('Unsent text stays in this tab.');return;}localDraft=value;session.draftText=value;dirty=true;generation++;status('Saving your place…');clearTimeout(timer);timer=setTimeout(()=>flush().catch(e=>status(e.message)),550);}
  async function flush(){clearTimeout(timer);await queue.catch(()=>{});if(!dirty)return;const text=localDraft,version=generation;await mutate('draft',{text});if(version===generation)dirty=false;else session.draftText=localDraft;status(dirty?'Saving your place…':'Your place is saved.');}
  async function send(event={}){
    if(busy){if(['pause','end'].includes(event.action)){pendingAction=event.action;status('Pausing after the current message is saved. You can leave this page now.');}return;}
    exerciseCleanup();exerciseCleanup=()=>{};setBusy(true);voiceCleanup();voiceCleanup=()=>{};
    try{await flush();status(session.aiConsent?'Paasaa is thinking…':'Finding your next step…');if(typeof event.value==='string'){const pending=el('div',undefined,'conversation-message patient-message');pending.append(el('span','You','message-author'),el('p',event.value));root.querySelector('.conversation-thread')?.append(pending);}const indicator=el('p',session.aiConsent?'Paasaa is thinking…':'Finding your next step…','conversation-thinking');indicator.setAttribute('role','status');root.querySelector('.conversation-thread')?.append(indicator);const log=root.querySelector('.conversation-thread');if(log)log.scrollTop=log.scrollHeight;const r=await mutate('turn',{...event,localContext:localChatContext()});dirty=false;voice=null;render();status(r.notice||'Your place is saved.');}
    catch(e){if(session.companion&&typeof event.value==='string')session.draftText=event.value;render();status(e.message);const retry=button('Retry this message',()=>{retry.remove();send(event);});root.append(retry);}
    finally{setBusy(false);if(active&&composer)composer.focus({preventScroll:true});if(pendingAction){const action=pendingAction;pendingAction=null;send({action});}}
  }
  function turnButton(text,event,cls=''){const b=button(text,()=>send(typeof event==='function'?event():event),cls);b.dataset.turn='true';return b;}
  async function resume(id){if(busy)return;setBusy(true);try{await flush();const r=await api('conversations/'+id);session=r.session;persisted=true;dirty=false;voice=null;render();}catch(e){status(e.message);}finally{setBusy(false);}}
  function consentControl(){
    const toggle=button(session.aiConsent?'Turn AI replies off':'Turn AI replies on',async()=>{
      if(busy)return;const enabled=!session.aiConsent,draft=session.draftText;setBusy(true);
      try{await flush();if(persisted)await mutate('consent',{enabled});else session.aiConsent=enabled;if(session.companion)session.draftText=draft;render();status(enabled?'AI replies are on.':'AI replies are off. Scripted support is available.');}
      catch(e){status('Could not change AI setting. '+e.message);}finally{setBusy(false);}
    },'chat-setting-button');toggle.dataset.edit='true';toggle.disabled=busy||!available;return toggle;
  }
  function preferences(){const detail=el('details',undefined,'conversation-settings');detail.append(el('summary','Privacy, AI & sources'));const label=el('p','AI replies use Groq. Turn them off in Chat settings to use scripted support.');
    detail.append(label,el('p','Messages save to your private account. Unsent free-chat text stays in this tab. Recognized intrusive-thought details are omitted from saved chat; automated detection can miss details. AI wording is optional. Tapping the mic sends recorded audio to Groq after you stop. The transcript goes into your draft; Send submits it. Paasaa does not store the audio. Paasaa is an AI self-help preview, not a therapist or a monitored service. Clinical review is pending, particularly for teens.','subtle'));
    for(const [title,href]of [['Beck Institute: collaborative CBT conversations','https://beckinstitute.org/blog/why-cbt-therapists-dont-challenge-clients-cognitions-and-why-it-matters/'],['NHS: thought records','https://www.nhs.uk/every-mind-matters/mental-wellbeing-tips/self-help-cbt-techniques/thought-record/'],['CCI: worry and uncertainty','https://www.cci.health.wa.gov.au/Resources/Looking-After-Yourself/Worry-and-Rumination']]){const a=el('a',title);a.href=href;a.target='_blank';a.rel='noopener noreferrer';detail.append(a,el('br'));}detail.append(el('p','These explain ingredients of the approach; they do not validate this AI or its outcomes.','subtle'));return detail;
  }
  function savedSessions(){const detail=el('details',undefined,'conversation-sessions');detail.append(el('summary','Your conversations'));if(!records.length)detail.append(el('p','Your conversations will appear here.'));for(const r of records){const row=el('div',undefined,'conversation-saved');row.append(button(r.title.slice(0,100),()=>resume(r.id)));const due=r.outcomeDueAt&&!r.outcome?.recordedAt&&Date.parse(r.outcomeDueAt)<=Date.now();row.append(el('small',due?'Outcome review due':r.outcomeDueAt&&!r.outcome?.recordedAt?'Review '+new Date(r.outcomeDueAt).toLocaleString():r.status));detail.append(row);}detail.append(button('Start a separate conversation',async()=>{if(busy)return;try{await flush();session=newConversation(session.aiConsent,true);persisted=false;dirty=false;voice=null;render();}catch(e){status(e.message);}}));return detail;}
  function summarySurface(surface){const review=el('div',undefined,'conversation-review');const source=session.state==='DETAILS'?session.pending.details:session.state==='PREVIOUS'?session.repeat?.answers||{}:session.answers;detailsInputs={};for(const [key,value]of Object.entries(source)){if(value===undefined)continue;const item=el('div',undefined,'conversation-note');item.append(el('span',fields[key]?.question||key.replace(/([A-Z])/g,' $1'),'subtle'));
      if(session.state==='DETAILS'){const input=el('textarea');input.value=value;input.maxLength=1500;input.setAttribute('aria-label',fields[key]?.question||key);detailsInputs[key]=input;item.append(input);}
      else {item.append(el('p',display(value)));if(fields[key]&&['SUMMARY','COMPLETE'].includes(session.state)){const edit=button('Edit',()=>{const form=el('form');const q=fields[key];const input=el(q.choices?'select':q.type==='slider'?'input':'textarea');input.setAttribute('aria-label','Edit '+q.question);if(q.choices)q.choices.forEach(c=>{const o=el('option',c.label);o.value=c.id;input.append(o);});if(q.type==='slider'){input.type='number';input.min=0;input.max=100;input.step=1;}else input.maxLength=6000;input.value=value??'';const save=el('button','Keep this edit');save.type='submit';form.append(input,save);form.onsubmit=async e=>{e.preventDefault();setBusy(true);try{await flush();await mutate('edit',{field:key,value:q.type==='slider'?(input.value===''?null:Number(input.value)):input.value});render();}catch(e){status(e.message);}finally{setBusy(false);}};item.replaceChildren(form);input.focus();});edit.dataset.edit='true';item.append(edit);}}
      review.append(item);
    }if(session.outcome){review.append(el('h3','What happened'),el('p',session.outcome.result),el('p',session.outcome.copingDescription||''),el('p',session.outcome.learning||''));}surface.append(review);
  }
  function render(){
    exerciseCleanup();exerciseCleanup=()=>{};voiceCleanup();voiceCleanup=()=>{};root.replaceChildren();root.className='flow-panel conversation-panel';
    const view=conversationView(session);const head=el('div',undefined,'conversation-head');head.append(el('h1','Talk to Paasaa'));const menu=el('details',undefined,'chat-popup');const menuButton=el('summary');menuButton.setAttribute('aria-label','Chat settings');menuButton.title='Chat settings';menuButton.append(icon('more'));const menuBody=el('div',undefined,'chat-popup-body');menuBody.append(el('p',session.aiConsent?'AI replies on':'AI replies off','chat-mode-label'),consentControl(),savedSessions(),preferences());menu.append(menuButton,menuBody);menu.onkeydown=e=>{if(e.key==='Escape'){menu.open=false;menuButton.focus();}};head.append(menu);root.append(head);
    if(session.companion&&!session.transcript.length){const welcome=el('div',undefined,'chat-welcome');welcome.append(el('h2','What’s going on?'),el('p','A little space to talk, reflect, or take one small step.'));const starters=el('div',undefined,'conversation-choices');starters.append(turnButton('I feel stuck',{value:'I feel stuck and can’t think right now.'}),turnButton('Work through a worry',{action:'reflect'}),button('Just talk',()=>composer?.focus()),button('Daily check-in',()=>{location.hash='#check-in';}));welcome.append(starters);root.append(welcome);}
    const phases=el('div',undefined,'conversation-phases');phases.setAttribute('aria-label','Conversation phase');for(const phase of ['STABILIZE','UNDERSTAND','WORK THROUGH','LEARN']){const n=el('span',phase.toLowerCase());if(phase===view.phase){n.className='current';n.setAttribute('aria-current','step');}phases.append(n);}if(!session.companion)root.append(phases);
    const thread=el('div',undefined,'conversation-thread');thread.setAttribute('role','log');thread.setAttribute('aria-label','Conversation with Paasaa');root.append(thread);
    const history=session.transcript.at(-1)?.role==='assistant'?session.transcript.slice(0,-1):session.transcript;
    for(const turn of history){const message=el('div',undefined,turn.role==='user'?'conversation-message patient-message':'conversation-message paasaa-message');message.append(el('span',turn.role==='user'?'You':'Paasaa','message-author'),el('p',turn.text));thread.append(message);}
    const surface=el('div',undefined,'conversation-turn paasaa-message');surface.append(el('span','Paasaa','message-author'));if(session.notice)surface.append(el('p',session.notice,'conversation-acknowledgment'));
    const prompt=el('p',session.aiMessage||view.message,'conversation-reply');surface.append(prompt);thread.append(surface);
    if(session.companion&&session.chatAction){const mount=el('div');surface.append(mount);exerciseCleanup=mountChatExercise(mount,session.chatAction,event=>send(event));}
    if(session.companion&&session.chatSafety==='urgent')surface.append(button('Get human support now',openSafety,'primary'));
    if(session.answers.prediction&&['WORK THROUGH','LEARN'].includes(view.phase)&&view.type!=='summary'){const card=el('div',undefined,'conversation-prediction');card.append(el('span','THE PREDICTION','eyebrow'),el('p',session.answers.prediction));surface.append(card);}
    composer=null;predictionInput=null;sliderValue=null;detailsInputs={};historyInputs=[];
    if(view.type==='safety'){surface.append(button('Open human support',openSafety,'primary'),el('p','If you’re a teen, a safe trusted adult or health professional can help you reach support.'));}
    if(['summary','previous'].includes(view.type))summarySurface(surface);
    if(view.type==='history'){for(const r of session.history){const label=el('label',undefined,'conversation-history-choice');const checkbox=el('input');checkbox.type='checkbox';checkbox.value=r.id;checkbox.disabled=!r.outcome;label.append(checkbox,document.createTextNode(r.prediction+' · '+(r.outcome?.result||'Outcome not recorded')));historyInputs.push(checkbox);surface.append(label);}}
    if(session.state==='WORK'&&session.field==='personalHistory'){const chosen=session.history.filter(r=>session.relatedIds.includes(r.id));const box=el('div',undefined,'conversation-prediction');for(const r of chosen)box.append(el('p',r.prediction+' — '+r.outcome.result));const binary=chosen.filter(r=>['Happened','Did not happen'].includes(r.outcome.result));if(binary.length>=5)box.append(el('p',`${binary.length} selected resolved yes/no predictions; the feared outcome happened in ${binary.filter(r=>r.outcome.result==='Happened').length}. Partial and unclear outcomes are excluded. These records do not predict this event.`));surface.append(box);}
    if(view.type==='prediction'){const label=el('label','Your prediction');predictionInput=el('textarea');predictionInput.value=session.draftText||session.pendingPrediction||'';predictionInput.rows=3;predictionInput.maxLength=6000;predictionInput.oninput=()=>saveDraft(predictionInput.value);label.append(predictionInput);surface.append(label);}
    if(view.type==='slider'){
      const label=el('label',view.unit||'Your estimate · 0–100');const output=el('output','Not answered','conversation-rating-value');const range=el('input');range.type='range';range.min=0;range.max=100;range.step=1;range.setAttribute('aria-label',view.message);const saved=session.draftText!==''?Number(session.draftText):null;sliderValue=Number.isInteger(saved)&&saved>=0&&saved<=100?saved:null;range.value=sliderValue??50;
      const sync=()=>{output.textContent=sliderValue===null?'Not answered':String(sliderValue)+(view.unit?.includes('%')?'%':' / 100');range.setAttribute('aria-valuetext',sliderValue===null?'Not answered; move the slider or choose zero':String(sliderValue));};range.oninput=()=>{sliderValue=Number(range.value);saveDraft(String(sliderValue));sync();};label.append(output,range);surface.append(label);const ends=el('div',undefined,'rating-labels');ends.append(el('span','0'),el('span','100'));surface.append(ends,button('Choose 0',()=>{sliderValue=0;range.value=0;saveDraft('0');sync();},'text-button'));sync();surface.append(turnButton('Keep this estimate',()=>({value:sliderValue}),'primary'));
    }
    if(view.type==='breathing'){const visual=el('div',undefined,'conversation-breath');visual.setAttribute('aria-hidden','true');surface.append(visual,el('p','Your own pace. No countdown to match.','subtle'));}
    if(view.type==='grounding'){const visual=el('div','◦','conversation-ground');visual.setAttribute('aria-hidden','true');surface.append(visual);}
    if(view.type==='datetime'){
      const label=el('label','Review date and local time');const date=el('input');date.type='datetime-local';date.setAttribute('aria-label','Review date and local time');label.append(date);surface.append(label,turnButton('Schedule my review',()=>({value:date.value?new Date(date.value).toISOString():''}),'primary'));
    }
    const choices=el('div',undefined,'conversation-choices');for(const c of view.choices){choices.append(turnButton(c.label,()=>({action:c.id,...(c.id==='confirm'?{prediction:predictionInput.value}:{}),...(c.id==='acceptDetails'?{details:Object.fromEntries(Object.entries(detailsInputs).map(([k,v])=>[k,v.value]))}:{}),...(c.id==='useHistory'?{ids:historyInputs.filter(n=>n.checked).map(n=>n.value)}:{})}),c.id==='complete'?'primary':''));}surface.append(choices);
    const showComposer=!['PAUSED','ENDED','COMPLETE','SAFETY','CHAT_PAUSED','CHAT_ENDED'].includes(session.state);
    if(showComposer){const form=el('form',undefined,'conversation-composer');const label=el('label',undefined);composer=el('textarea');composer.setAttribute('aria-label','Message Paasaa');composer.rows=1;composer.maxLength=6000;composer.placeholder='Tell me what’s on your mind…';const freeText=['text','choices','grounding','breathing'].includes(view.type);composer.value=freeText?session.draftText||'':'';composer.oninput=()=>{if(freeText)saveDraft(composer.value);};label.append(composer);const sendButton=el('button',undefined,'primary chat-icon-button');sendButton.append(icon('send'));sendButton.setAttribute('aria-label','Send message');sendButton.title='Send message';sendButton.type='submit';sendButton.dataset.turn='true';const micButton=button('',()=>{},'chat-icon-button');micButton.append(icon('mic'));micButton.setAttribute('aria-label','Record voice message');micButton.setAttribute('aria-describedby','chat-voice-disclosure');micButton.title='Record voice message';micButton.dataset.requiresAi='true';micButton.dataset.turn='true';form.append(label,micButton,sendButton);form.onsubmit=e=>{e.preventDefault();if(composer.value.trim()){const text=composer.value.trim();const value=view.type==='slider'&&/^\d{1,3}%?$/.test(text)?Number(text.replace('%','')):composer.value;send({value,voice:voice&&typeof value==='string'?{...voice,patientApprovedText:value}:undefined});}};const dock=el('div',undefined,'conversation-dock');dock.append(form,el('p','Enter to send / Shift + Enter for a new line','composer-hint'));root.append(dock);composer.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();form.requestSubmit();}};
      const voiceStatus=el('p','', 'chat-voice-status');voiceStatus.setAttribute('role','status');
      const cancelVoice=button('Cancel recording',()=>{voiceCleanup();render();status('Recording discarded.');},'text-button');cancelVoice.hidden=true;
      const disclosure=el('p','Mic: audio goes to Groq for transcription. Stop recording to place text in your draft.','chat-disclaimer');disclosure.id='chat-voice-disclosure';
      const aiNotice=el('p',!available?'AI is unavailable. Scripted support is available.':session.aiConsent?'Replies are generated by AI · Prototype, not a therapist. Sending shares conversation context with Groq.':'AI replies are off · Scripted support only. Change this in Chat settings.','chat-disclaimer');
      dock.append(voiceStatus,cancelVoice,disclosure,aiNotice);
      const voiceController=createChatVoice({onState:(state,message)=>{const recording=state==='recording';micButton.replaceChildren(icon(recording?'stop':'mic'));micButton.setAttribute('aria-label',recording?'Stop recording':'Record voice message');micButton.title=recording?'Stop recording':'Record voice message';micButton.classList.toggle('is-recording',recording);micButton.disabled=!available||['requesting','transcribing'].includes(state);sendButton.disabled=state!=='idle';cancelVoice.hidden=state==='idle';voiceStatus.textContent=message;},onTranscript:raw=>{const value=[composer.value.trim(),raw.trim()].filter(Boolean).join(' ');if(value.length>6000){throw Error('Voice text is too long. Please record a shorter message.');}composer.value=value;voice={rawTranscript:raw,cleanedTranscript:null,patientApprovedText:value};if(freeText)saveDraft(value);composer.focus();}});
      micButton.onclick=()=>voiceController.toggle();voiceCleanup=()=>voiceController.dispose();
      const submit=form.onsubmit;form.onsubmit=e=>{if(voiceController.state!=='idle'){e.preventDefault();return;}submit(e);};

    }
    if(view.canSkip)surface.append(turnButton('Leave this unanswered',{action:'skip'},'text-button'));
    statusNode=el('p',persisted?'Your place is saved.':'Messages save to your private account; unsent chat stays in this tab.','conversation-save');statusNode.setAttribute('role','status');root.append(statusNode);
    const control=el('div',undefined,'conversation-controls');for(const [id,label]of (session.companion?[['reflect','Work through a worry'],['pause','Pause'],['another','Try another way'],['restart','Start again'],['end','End for now']]:[['chat','Chat freely'],['pause','Pause'],['another','Try another way'],['restart','Start again'],['reflect','Talk about the worry'],['end','End for now']]))control.append(button(label,()=>send({action:id}),'text-button'));if(!session.companion&&session.checkpoints.length)control.append(button('Go back',()=>send({action:'back'}),'text-button'));menuBody.append(control);root.append(button('I need human support',openSafety,'text-button chat-human-support'));
    setBusy(busy);requestAnimationFrame(()=>{thread.scrollTop=thread.scrollHeight;if(active&&composer&&!busy)composer.focus({preventScroll:true});});
  }
  async function home(){active=true;if(!await requireAccount(root,home))return;if(loaded){render();return;}loaded=true;root.replaceChildren(el('p','Finding your place…'));try{const [saved,cap]=await Promise.all([api('conversations'),api('status')]);records=saved.records;available=cap.ai;const latest=records.find(r=>r.companion&&['active','paused'].includes(r.status));if(latest){const r=await api('conversations/'+latest.id);session=r.session;persisted=true;}render();}catch(e){loaded=false;root.replaceChildren(el('h1','Talk to Paasaa'),el('p',e.message),button('Try again',home),button('Use immediate support',()=>{location.hash='#support';}));}}
  window.addEventListener('beforeunload',event=>{if(dirty||busy||session.companion&&session.draftText){event.preventDefault();event.returnValue='';}});
  return {home,leave(){active=false;exerciseCleanup();voiceCleanup();flush().catch(e=>status(e.message));},clear(){exerciseCleanup();voiceCleanup();loaded=false;persisted=false;dirty=false;session=newConversation(true,true);}};
}
