import {newConversation,conversationView,fields} from './conversation-model.js';
import {mountVoice} from './voice.js';
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const button=(text,fn,cls='')=>{const b=el('button',text,cls);b.type='button';b.onclick=fn;return b;};
const api=async(path,body)=>{const r=await fetch('/api/'+path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});let d;try{d=await r.json();}catch{throw Error('The connection is unavailable. Your words remain here.');}if(!r.ok)throw Error(d.error||'Could not save. Your words remain here.');return d;};
const display=v=>v===null||v===undefined||v===''?'Not answered':String(v);

export function createChat(_checkin,openSafety){
  const root=document.getElementById('chat-screen');let session=newConversation(),persisted=false,available=false,loaded=false,active=false,busy=false,records=[],dirty=false,localDraft='',generation=0,timer,queue=Promise.resolve(),voiceCleanup=()=>{},voice=null,statusNode,composer,sliderValue=null,predictionInput,detailsInputs={},historyInputs=[],pendingAction=null;
  const status=message=>{if(statusNode)statusNode.textContent=message;};
  function setBusy(value){busy=value;root.setAttribute('aria-busy',String(value));root.querySelectorAll('input,textarea,select,button[data-turn],button[data-edit]').forEach(n=>n.disabled=value||n.dataset.requiresAi==='true'&&!available);}
  async function ensure(){if(!persisted){const r=await api('conversations',{aiConsent:session.aiConsent});session=r.session;persisted=true;}}
  function mutate(op,body){const run=queue.catch(()=>{}).then(async()=>{await ensure();const r=await api(`conversations/${session.id}/${op}`,{...body,revision:session.revision});session=r.session;records=[{id:session.id,state:session.state,title:session.answers.worry||session.openingMessage||'A moment for yourself',status:session.status,outcomeDueAt:session.outcomeDueAt,outcome:session.outcome},...records.filter(x=>x.id!==session.id)];return r;});queue=run;return run;}
  function saveDraft(value){localDraft=value;session.draftText=value;dirty=true;generation++;status('Saving your place…');clearTimeout(timer);timer=setTimeout(()=>flush().catch(e=>status(e.message)),550);}
  async function flush(){clearTimeout(timer);await queue.catch(()=>{});if(!dirty)return;const text=localDraft,version=generation;await mutate('draft',{text});if(version===generation)dirty=false;else session.draftText=localDraft;status(dirty?'Saving your place…':'Your place is saved.');}
  async function send(event={}){
    if(busy){if(['pause','end'].includes(event.action)){pendingAction=event.action;status('Pausing after the current message is saved. You can leave this page now.');}return;}
    setBusy(true);voiceCleanup();voiceCleanup=()=>{};
    try{await flush();status('One moment…');const r=await mutate('turn',event);dirty=false;voice=null;render();status(r.notice||'Your place is saved.');}
    catch(e){render();status(e.message);}
    finally{setBusy(false);if(pendingAction){const action=pendingAction;pendingAction=null;send({action});}}
  }
  function turnButton(text,event,cls=''){const b=button(text,()=>send(typeof event==='function'?event():event),cls);b.dataset.turn='true';return b;}
  async function resume(id){if(busy)return;setBusy(true);try{await flush();const r=await api('conversations/'+id);session=r.session;persisted=true;dirty=false;voice=null;render();}catch(e){status(e.message);}finally{setBusy(false);}}
  function preferences(){const detail=el('details',undefined,'conversation-settings');detail.append(el('summary','Privacy, AI & sources'));const label=el('label',undefined,'conversation-consent');const toggle=el('input');toggle.type='checkbox';toggle.checked=session.aiConsent;toggle.dataset.consent='true';toggle.disabled=!available;toggle.dataset.requiresAi='true';toggle.onchange=async()=>{const enabled=toggle.checked;setBusy(true);try{await flush();if(persisted)await mutate('consent',{enabled});else session.aiConsent=enabled;status(enabled?'AI wording enabled. Only relevant context is sent when you respond.':'AI wording off. Guided conversation remains available.');}catch(e){status(e.message);toggle.checked=session.aiConsent;}finally{setBusy(false);root.querySelectorAll('input[data-consent]').forEach(n=>n.checked=session.aiConsent);}};label.append(toggle,document.createTextNode('Use Groq to adapt questions using the relevant parts of this conversation.'));
    detail.append(label,el('p','This conversation and drafts save to your private account. AI wording is optional. Voice has its own consent and review. Paasaa is an AI self-help preview, not a therapist or a monitored service. Clinical review is pending, particularly for teens.','subtle'));
    for(const [title,href]of [['NHS: thought records','https://www.nhs.uk/every-mind-matters/mental-wellbeing-tips/self-help-cbt-techniques/thought-record/'],['CCI: worry and uncertainty','https://www.cci.health.wa.gov.au/Resources/Looking-After-Yourself/Worry-and-Rumination']]){const a=el('a',title);a.href=href;a.target='_blank';a.rel='noopener noreferrer';detail.append(a,el('br'));}detail.append(el('p','These explain ingredients of the approach; they do not validate this AI or its outcomes.','subtle'));return detail;
  }
  function savedSessions(){const detail=el('details',undefined,'conversation-sessions');detail.append(el('summary','Your conversations'));if(!records.length)detail.append(el('p','Your conversations will appear here.'));for(const r of records){const row=el('div',undefined,'conversation-saved');row.append(button(r.title.slice(0,100),()=>resume(r.id)));const due=r.outcomeDueAt&&!r.outcome?.recordedAt&&Date.parse(r.outcomeDueAt)<=Date.now();row.append(el('small',due?'Outcome review due':r.outcomeDueAt&&!r.outcome?.recordedAt?'Review '+new Date(r.outcomeDueAt).toLocaleString():r.status));detail.append(row);}detail.append(button('Start a separate conversation',async()=>{if(busy)return;try{await flush();session=newConversation(session.aiConsent);persisted=false;dirty=false;voice=null;render();}catch(e){status(e.message);}}));return detail;}
  function summarySurface(surface){const review=el('div',undefined,'conversation-review');const source=session.state==='DETAILS'?session.pending.details:session.state==='PREVIOUS'?session.repeat?.answers||{}:session.answers;detailsInputs={};for(const [key,value]of Object.entries(source)){if(value===undefined)continue;const item=el('div',undefined,'conversation-note');item.append(el('span',fields[key]?.question||key.replace(/([A-Z])/g,' $1'),'subtle'));
      if(session.state==='DETAILS'){const input=el('textarea');input.value=value;input.maxLength=1500;input.setAttribute('aria-label',fields[key]?.question||key);detailsInputs[key]=input;item.append(input);}
      else {item.append(el('p',display(value)));if(fields[key]&&['SUMMARY','COMPLETE'].includes(session.state)){const edit=button('Edit',()=>{const form=el('form');const q=fields[key];const input=el(q.choices?'select':q.type==='slider'?'input':'textarea');input.setAttribute('aria-label','Edit '+q.question);if(q.choices)q.choices.forEach(c=>{const o=el('option',c.label);o.value=c.id;input.append(o);});if(q.type==='slider'){input.type='number';input.min=0;input.max=100;input.step=1;}else input.maxLength=6000;input.value=value??'';const save=el('button','Keep this edit');save.type='submit';form.append(input,save);form.onsubmit=async e=>{e.preventDefault();setBusy(true);try{await flush();await mutate('edit',{field:key,value:q.type==='slider'?(input.value===''?null:Number(input.value)):input.value});render();}catch(e){status(e.message);}finally{setBusy(false);}};item.replaceChildren(form);input.focus();});edit.dataset.edit='true';item.append(edit);}}
      review.append(item);
    }if(session.outcome){review.append(el('h3','What happened'),el('p',session.outcome.result),el('p',session.outcome.copingDescription||''),el('p',session.outcome.learning||''));}surface.append(review);
  }
  function render(){
    voiceCleanup();voiceCleanup=()=>{};root.replaceChildren();root.className='flow-panel conversation-panel';
    const view=conversationView(session);const head=el('div',undefined,'conversation-head');head.append(el('h1','Talk to Paasaa'),savedSessions());root.append(head);
    const phases=el('div',undefined,'conversation-phases');phases.setAttribute('aria-label','Conversation phase');for(const phase of ['STABILIZE','UNDERSTAND','WORK THROUGH','LEARN']){const n=el('span',phase.toLowerCase());if(phase===view.phase){n.className='current';n.setAttribute('aria-current','step');}phases.append(n);}root.append(phases);
    const history=session.transcript.slice(0,-1);if(history.length>1){const previous=el('details',undefined,'conversation-history');previous.append(el('summary','Earlier in this conversation'));for(const turn of history.slice(0,-1)){const p=el('p',turn.text,turn.role==='user'?'patient-message':'previous-paasaa');previous.append(p);}root.append(previous);}
    const last=session.transcript.filter(t=>t.role==='user').at(-1);if(last)root.append(el('p',last.text,'patient-message'));
    const surface=el('div',undefined,'conversation-turn');surface.setAttribute('aria-live','polite');surface.append(el('span','PAASAA','eyebrow'));if(session.notice)surface.append(el('p',session.notice,'conversation-acknowledgment'));
    const prompt=el('h2',session.aiMessage||view.message);prompt.tabIndex=-1;surface.append(prompt);root.append(surface);
    if(session.answers.prediction&&['WORK THROUGH','LEARN'].includes(view.phase)&&view.type!=='summary'){const card=el('div',undefined,'conversation-prediction');card.append(el('span','THE PREDICTION','eyebrow'),el('p',session.answers.prediction));surface.append(card);}
    composer=null;predictionInput=null;sliderValue=null;detailsInputs={};historyInputs=[];
    if(view.type==='safety'){surface.append(button('Open human support',openSafety,'primary'),el('p','If you’re a teen, a safe trusted adult or health professional can help you reach support.'));}
    if(['summary','previous'].includes(view.type))summarySurface(surface);
    if(view.type==='history'){for(const r of session.history){const label=el('label',undefined,'conversation-history-choice');const checkbox=el('input');checkbox.type='checkbox';checkbox.value=r.id;checkbox.disabled=!r.outcome;label.append(checkbox,document.createTextNode(r.prediction+' · '+(r.outcome?.result||'Outcome not recorded')));historyInputs.push(checkbox);surface.append(label);}}
    if(session.state==='WORK'&&session.field==='personalHistory'){const chosen=session.history.filter(r=>session.relatedIds.includes(r.id));const box=el('div',undefined,'conversation-prediction');for(const r of chosen)box.append(el('p',r.prediction+' — '+r.outcome.result));const binary=chosen.filter(r=>['Happened','Did not happen'].includes(r.outcome.result));if(binary.length>=5)box.append(el('p',`${binary.length} selected resolved yes/no predictions; the feared outcome happened in ${binary.filter(r=>r.outcome.result==='Happened').length}. Partial and unclear outcomes are excluded. These records do not predict this event.`));surface.append(box);}
    if(view.type==='prediction'){const label=el('label','Your prediction');predictionInput=el('textarea');predictionInput.value=session.draftText||session.pendingPrediction||'';predictionInput.rows=3;predictionInput.maxLength=6000;predictionInput.oninput=()=>saveDraft(predictionInput.value);label.append(predictionInput);surface.append(label);}
    if(view.type==='slider'){
      const label=el('label',view.unit||'Your estimate · 0–100');const output=el('output','Not answered','conversation-rating-value');const range=el('input');range.type='range';range.min=0;range.max=100;range.step=1;range.setAttribute('aria-label',view.message);const saved=session.draftText!==''?Number(session.draftText):null;sliderValue=Number.isInteger(saved)&&saved>=0&&saved<=100?saved:null;range.value=sliderValue??50;
      const sync=()=>{output.textContent=sliderValue===null?'Not answered':String(sliderValue)+(view.unit?.includes('%')?'%':' / 100');range.setAttribute('aria-valuetext',sliderValue===null?'Not answered; move the slider or choose zero':String(sliderValue));};range.oninput=()=>{sliderValue=Number(range.value);saveDraft(String(sliderValue));sync();};label.append(output,range);surface.append(label);const ends=el('div',undefined,'rating-labels');ends.append(el('span','0'),el('span','100'));surface.append(ends,button('Choose 0',()=>{sliderValue=0;range.value=0;saveDraft('0');sync();},'text-button'));sync();surface.append(turnButton('Keep this estimate',()=>({value:sliderValue}),'primary'));
    }
    if(view.type==='breathing'){const visual=el('div',undefined,'conversation-breath');visual.setAttribute('aria-hidden','true');surface.append(visual,el('p','Your own pace. No countdown to match.','subtle'));}
    if(view.type==='grounding'){const visual=el('div','◦','conversation-ground');visual.setAttribute('aria-hidden','true');surface.append(visual);}
    if(view.type==='datetime'){
      const label=el('label','Review date and local time');const date=el('input');date.type='datetime-local';date.setAttribute('aria-label','Review date and local time');label.append(date);surface.append(label,turnButton('Schedule my review',()=>({value:date.value?new Date(date.value).toISOString():''}),'primary'));
    }
    const choices=el('div',undefined,'conversation-choices');for(const c of view.choices){choices.append(turnButton(c.label,()=>({action:c.id,...(c.id==='confirm'?{prediction:predictionInput.value}:{}),...(c.id==='acceptDetails'?{details:Object.fromEntries(Object.entries(detailsInputs).map(([k,v])=>[k,v.value]))}:{}),...(c.id==='useHistory'?{ids:historyInputs.filter(n=>n.checked).map(n=>n.value)}:{})}),c.id==='complete'?'primary':''));}surface.append(choices);
    const showComposer=['text','choices','grounding','breathing'].includes(view.type)&&!['PAUSED','ENDED','COMPLETE'].includes(session.state);
    if(showComposer){const form=el('form',undefined,'conversation-composer');const label=el('label','Your response');composer=el('textarea');composer.rows=2;composer.maxLength=6000;composer.placeholder=session.state==='READINESS'?'You can start with what’s on your mind.':'A few words are enough.';composer.value=session.draftText||'';composer.oninput=()=>saveDraft(composer.value);label.append(composer);const sendButton=el('button','Send','primary');sendButton.type='submit';sendButton.dataset.turn='true';form.append(label,sendButton);form.onsubmit=e=>{e.preventDefault();if(composer.value.trim())send({value:composer.value,voice:voice?{...voice,patientApprovedText:composer.value}:undefined});};surface.append(form);
      const voiceDetails=el('details',undefined,'conversation-voice');voiceDetails.append(el('summary','Use my voice'));const mount=el('div');voiceDetails.append(mount);surface.append(voiceDetails);voiceDetails.ontoggle=()=>{if(voiceDetails.open&&!mount.childElementCount)voiceCleanup=mountVoice(mount,(value,metadata)=>{composer.value=value;voice=metadata;saveDraft(value);},{available});};
    }
    if(view.canSkip)surface.append(turnButton('Leave this unanswered',{action:'skip'},'text-button'));
    statusNode=el('p',persisted?'Your place is saved.':'Your conversation saves to your private account.','conversation-save');statusNode.setAttribute('role','status');root.append(statusNode);
    if(!session.aiConsent&&available&&session.state==='READINESS'){const label=el('label',undefined,'conversation-consent');const toggle=el('input');toggle.type='checkbox';toggle.dataset.consent='true';toggle.onchange=async()=>{root.querySelectorAll('input[data-consent]').forEach(n=>n.checked=toggle.checked);session.aiConsent=toggle.checked;if(persisted){try{await mutate('consent',{enabled:toggle.checked});}catch(e){status(e.message);}}};label.append(toggle,document.createTextNode('Let AI adapt the conversation. Relevant text will be sent to Groq.'));root.append(label);}
    const control=el('div',undefined,'conversation-controls');for(const [id,label]of [['pause','Pause'],['another','Try another way'],['restart','Start again'],['reflect','Talk about the worry'],['end','End for now']])control.append(button(label,()=>send({action:id}),'text-button'));if(session.checkpoints.length)control.append(button('Go back',()=>send({action:'back'}),'text-button'));root.append(control,preferences(),button('I need human support',openSafety,'text-button'));
    if(active)prompt.focus({preventScroll:true});setBusy(busy);
  }
  async function home(){active=true;if(loaded){render();return;}loaded=true;root.replaceChildren(el('p','Finding your place…'));try{const [saved,cap]=await Promise.all([api('conversations'),api('status')]);records=saved.records;available=cap.ai;const latest=records.find(r=>r.outcomeDueAt&&!r.outcome?.recordedAt&&Date.parse(r.outcomeDueAt)<=Date.now())||records.find(r=>['active','paused'].includes(r.status));if(latest){const r=await api('conversations/'+latest.id);session=r.session;persisted=true;}render();}catch(e){loaded=false;root.replaceChildren(el('h1','Talk to Paasaa'),el('p',e.message),button('Try again',home),button('Use immediate support',()=>{location.hash='#support';}));}}
  window.addEventListener('beforeunload',event=>{if(dirty||busy){event.preventDefault();event.returnValue='';}});
  return {home,leave(){active=false;voiceCleanup();flush().catch(e=>status(e.message));},clear(){voiceCleanup();loaded=false;persisted=false;dirty=false;session=newConversation();}};
}
