import {authConfig,accessToken,requireAccount} from './auth.js';
import {apiFetch} from './api-client.js';
import {MOODS,localDay,moodWeek} from './mood-model.js';
import {translate as t,getLanguage} from './i18n.js';
import {mountSafetyList} from './safety-resources.js';
const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
const link=(label,href,cls='well-link')=>{const a=el('a',label,cls);a.href=href;return a;};
const button=(label,fn,cls='')=>{const b=el('button',label,cls);b.type='button';b.onclick=fn;return b;};
const card=(title,cls='')=>{const c=el('article',undefined,'well-card '+cls);c.append(el('h2',title));return c;};
async function api(path,body){const r=await apiFetch('/api/'+path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Object.assign(Error(d.error||'Unable to load saved records.'),{status:r.status});return d;}
function intro(root,title,copy){const h=el('h1',title);h.tabIndex=-1;root.append(el('p','YOUR PERSONAL SPACE','eyebrow'),h,el('p',copy,'well-intro'));}
function dateLabel(day){return new Date(day+'T12:00:00').toLocaleDateString(getLanguage(),{month:'short',day:'numeric'});}
function week(records){const c=card('Your week','week-card');c.append(el('p','A little room to notice how you feel.','subtle'));const chart=el('div',undefined,'mood-week');chart.setAttribute('role','list');chart.setAttribute('aria-label',t('Your week'));
  for(const {day,record}of moodWeek(records)){const mood=MOODS.find(m=>m.id===record?.mood);const slot=el('div',undefined,'mood-day');slot.setAttribute('role','listitem');slot.append(el('span',dateLabel(day),'mood-date'),el('span',mood?.symbol||'—','mood-symbol'),el('span',t(mood?.label||'No entry')));chart.append(slot);}c.append(chart,el('p','Mood categories, not scores. Blank days mean no entry. One check-in per day; edits replace that day’s entry.','well-caption'));if(!records.length)c.append(el('p','Your mood patterns will appear here as you check in.'),link('Make your first check-in','#home'));return c;}
function noteState(c,message,retry){const p=el('p',message,'well-error');p.setAttribute('role','status');c.append(p);if(retry)c.append(button('Try again',retry));}
function moodCard(records,onSaved){const c=card('How are you feeling today?','mood-card');const day=localDay();let saved=records.find(r=>r.day===day),selected=saved?.mood||null,busy=false;const status=el('p',saved?'Saved for today. You can change your entry.':'No right or wrong answer.','mood-feedback');status.setAttribute('role','status');const choices=el('div',undefined,'mood-options');choices.setAttribute('role','group');choices.setAttribute('aria-label',t('How are you feeling today?'));
  const noteDetails=el('details',undefined,'mood-note'),note=el('textarea');note.maxLength=2000;note.rows=2;note.value=saved?.note||'';note.setAttribute('aria-label',t('Optional note'));const label=el('label','Optional note');label.append(note);noteDetails.append(el('summary','Add a note'),label);noteDetails.open=!!saved?.note;
  const save=button(saved?'Update check-in':'Save check-in',async()=>{if(busy||!selected)return;busy=true;save.disabled=true;for(const b of choices.children)b.disabled=true;note.disabled=true;status.textContent=t('Saving…');try{saved=await api('moods',{day,mood:selected,note:note.value,revision:saved?.revision||0});status.textContent=t('Check-in saved.');save.textContent=t('Update check-in');onSaved(saved);}catch(e){status.textContent=t(e.status===409?'This check-in changed in another tab. Reload before saving.':'Could not save. Your entry is still here; try again.');}finally{busy=false;save.disabled=false;for(const b of choices.children)b.disabled=false;note.disabled=false;}},'primary');save.disabled=!selected;
  for(const mood of MOODS){const b=button('',()=>{selected=mood.id;for(const child of choices.children)child.setAttribute('aria-pressed',String(child===b));save.disabled=false;status.textContent=t(selected==='anxious'?'Want to share what’s been worrying you?':'You can add a note, or leave it here.');});b.append(el('span',mood.symbol,'mood-emoji'),el('span',mood.label));b.setAttribute('aria-pressed',String(selected===mood.id));choices.append(b);}
  const actions=el('div',undefined,'well-actions');actions.append(save,link('Talk to Paasaa','#chat'));c.append(choices,status,noteDetails,actions,el('p','Saves to your account. Notes are not sent to AI or a clinician.','well-caption'));return c;}
function tool(title,description,href,icon,label){const c=card(title,'quick-card');c.prepend(el('span',icon,'tool-icon'));c.append(el('p',description),link(label,href));return c;}
function continuation(worries,conversations){const c=card('Continue where you left off');const r=worries?.find(r=>r.status!=='complete'&&!r.safetyPaused);const chat=conversations?.find(r=>r.status==='active'||r.status==='paused');if(r){const title=el('p',r.answers?.worry||'An unfinished worry','record-title');title.dataset.i18nSkip='true';c.append(title,link('Continue your reflection','#worry/'+encodeURIComponent(r.id)));}else if(chat){c.append(el('p','Your recent conversation'),link('Continue chatting','#chat/'+encodeURIComponent(chat.id)));}else c.append(el('p','Nothing to pick up right now. Start whenever you’re ready.'));return c;}
export function createWellness(){
  let generation=0;
  async function account(){const root=document.getElementById('account-screen');root.replaceChildren();if(await requireAccount(root,account))location.hash='#home';}
  function landing(root){root.replaceChildren();intro(root,'Your space to feel better.','A little support for everyday worries. A place to pause, reflect, and talk.');const hero=card('Meet Paasaa','chat-cta public-hero');hero.append(el('p','An AI support companion, with optional check-ins and self-help tools.'),link('Get started','#account','well-primary'),link('Sign in','#account'));root.append(hero);const grid=el('div',undefined,'quick-grid');grid.append(tool('Talk','Start anywhere.','#chat','◌','Talk to Paasaa'),tool('Reflect','Make space for your day.','#account','✎','Get started'),tool('Pause','A moment at your own pace.','#breathe','≈','Feel calmer'));root.append(grid,el('p','Self-help prototype for ages 13+. Not a therapist. Clinician review and notifications are not connected.','well-notice'),link('Privacy, safety & support','#help'));}
  async function home(){const root=document.getElementById('home-screen'),token=++generation;root.replaceChildren(el('p','Loading your space…','loading-state'));try{if(await authConfig()){if(!await accessToken()){if(token===generation)landing(root);return;}if(!await requireAccount(root,home))return;}}catch{root.replaceChildren();noteState(root,'Account connection is unavailable.',home);return;}
    const results=await Promise.allSettled(['moods','worries','conversations'].map(path=>api(path)));if(token!==generation)return;root.replaceChildren();const hour=new Date().getHours();root.append(el('p',hour<12?'Good morning':hour<17?'Good afternoon':'Good evening','well-greeting'));intro(root,'Your space to feel better.','Check in with yourself, reflect on your day, or talk things through.');const layout=el('div',undefined,'well-grid'),main=el('div',undefined,'well-main'),aside=el('div',undefined,'well-aside');let moods=results[0].status==='fulfilled'?results[0].value.records:null;const worries=results[1].status==='fulfilled'?results[1].value.records:null,conversations=results[2].status==='fulfilled'?results[2].value.records:null;
    let chart=moods?week(moods):card('Your week');
    if(moods)main.append(moodCard(moods,saved=>{moods=[saved,...moods.filter(r=>r.id!==saved.id)];const replacement=week(moods);chart.replaceWith(replacement);chart=replacement;}));else{const c=card('How are you feeling today?');noteState(c,'Check-ins could not load. Try again before saving.',home);main.append(c);noteState(chart,'Mood history is unavailable.',home);}
    const chat=card('Talk to Paasaa','chat-cta');chat.prepend(el('span','◌','chat-orbit'));chat.append(el('p','Have something on your mind? You can start anywhere.'),link(conversations?.length?'Continue chatting':'Start a conversation','#chat','well-primary'));main.append(chat,chart);
    aside.append(tool('Feel calmer','Try a short grounding or breathing exercise.','#support','≈','Get started'),tool('Work through a worry','Make sense of what’s bothering you.','#worry','✎','Start reflecting'));const cont=continuation(worries,conversations);if(!worries||!conversations)noteState(cont,'Some activity could not load.',home);aside.append(cont,link('Detailed daily check-in · on this device','#check-in'));layout.append(main,aside);root.append(layout,el('p','Self-help prototype for ages 13+. Not a therapist. Clinician review and notifications are not connected.','well-notice'));
  }
  async function progress(){const root=document.getElementById('progress-screen');if(!await requireAccount(root,progress))return;const token=++generation;root.replaceChildren(el('p','Loading your progress…','loading-state'));const results=await Promise.allSettled(['moods','worries','conversations'].map(path=>api(path)));if(token!==generation)return;root.replaceChildren();intro(root,'Your progress, at your pace.','Your own observations. No scores to chase.');const moods=results[0].status==='fulfilled'?results[0].value.records:null;if(moods)root.append(week(moods));else noteState(root,'Mood history is unavailable.',progress);
    const history=card('Mood history');if(moods){const filter=el('select');filter.setAttribute('aria-label',t('Date range'));for(const [value,label]of [['7','Last 7 days'],['30','Last 30 days'],['all','All available entries']]){const o=el('option',t(label));o.value=value;filter.append(o);}const table=el('table',undefined,'mood-history');const draw=()=>{table.replaceChildren();const head=el('tr');for(const s of ['Date','Mood','Note','Action'])head.append(el('th',t(s)));table.append(head);const cutoff=new Date();cutoff.setDate(cutoff.getDate()-Number(filter.value)+1);const rows=moods.filter(r=>filter.value==='all'||r.day>=localDay(cutoff)).sort((a,b)=>b.day.localeCompare(a.day));for(const r of rows){const tr=el('tr');const note=el('td',r.note||'—');note.dataset.i18nSkip='true';tr.append(el('td',new Date(r.day+'T12:00:00').toLocaleDateString(getLanguage(),{year:'numeric',month:'short',day:'numeric'})),el('td',t(MOODS.find(m=>m.id===r.mood)?.label||'Not sure')),note);const action=el('td');action.append(button('Edit',()=>editMood(history,r,progress)));tr.append(action);table.append(tr);}if(!rows.length){const tr=el('tr'),td=el('td',t('No entries in this period.'));td.colSpan=4;tr.append(td);table.append(tr);}};filter.onchange=draw;draw();history.append(filter,table,el('p','Showing up to 200 most recently updated entries. Detailed on-device check-ins stay separate.','well-caption'),link('Detailed daily check-in · on this device','#check-in'));root.append(history);}
    for(const [index,title,route]of [[1,'Worries & reflections','worry'],[2,'Conversations','chat']]){const c=card(title);if(results[index].status==='rejected')noteState(c,'Some activity could not load.',progress);else{const records=results[index].value.records;if(!records.length)c.append(el('p','Nothing here yet. Start whenever you’re ready.'));for(const r of records){const row=el('div',undefined,'activity-row'),title=el('span',r.title||r.answers?.worry||'An unfinished worry');title.dataset.i18nSkip='true';const meta=el('small',r.status==='complete'?'Saved reflection':r.status==='paused'?'Paused':'In progress');row.append(title,meta,link('Open','#'+route+'/'+encodeURIComponent(r.id)));c.append(row);}c.append(link(route==='chat'?'Talk to Paasaa':'Start reflecting','#'+route));}root.append(c);}
    const care=card('Care & exercises');care.append(el('p','Clinician-approved care plans are not connected. Optional self-help tools remain available.'),link('Feel calmer','#support'));root.append(care);
  }
  function editMood(root,r,done){root.querySelector('.mood-editor')?.remove();const form=el('form',undefined,'mood-editor');const select=el('select');select.setAttribute('aria-label',t('Mood'));for(const m of MOODS){const o=el('option',t(m.label));o.value=m.id;select.append(o);}select.value=r.mood;const note=el('textarea');note.value=r.note;note.maxLength=2000;note.setAttribute('aria-label',t('Optional note'));const save=el('button','Update check-in','primary');save.type='submit';const status=el('p');status.setAttribute('role','status');let busy=false;form.append(el('h3',dateLabel(r.day)),select,note,save,button('Cancel',()=>form.remove()),status);form.onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;save.disabled=true;try{await api('moods',{day:r.day,mood:select.value,note:note.value,revision:r.revision});await done();const success=el('p','Check-in saved.','well-success');success.setAttribute('role','status');document.getElementById('progress-screen').prepend(success);}catch{status.textContent=t('Could not save. Your entry is still here; try again.');}finally{busy=false;save.disabled=false;}};root.append(form);select.focus();}
  function help(){const root=document.getElementById('help-screen');root.replaceChildren();intro(root,'Support, when you need it.','Know what is available, and how your information is used.');const urgent=card('Emergency & crisis resources','support-resources');urgent.append(el('p','If there is immediate danger, contact emergency services. Paasaa cannot contact help for you.'));const list=el('ul');mountSafetyList(list);urgent.append(list);root.append(urgent);for(const [title,copy]of [
    ['What Paasaa can help with','Everyday conversation, noticing feelings, and optional worry, grounding and breathing tools.'],
    ['Care & monitoring','Chats are not continuously monitored. Clinician review, working hours, on-call coverage and notifications are not connected.'],
    ['Privacy & consent','Account records are private to your sign-in. Chat uses Groq when AI is on; turn it off in chat settings. Mood notes are not sent to AI.'],
    ['For younger users','Intended for ages 13+. Adolescent clinical services are not enabled. No automatic caregiver access is provided; do not assume clinical confidentiality. A trusted adult can help you find appropriate care.'],
    ['Language & account','Choose your interface language in Profile & settings. Translations are a preview, not clinically reviewed guidance.']]){const c=card(title);c.append(el('p',copy));root.append(c);}root.append(button('Privacy & saved data',()=>document.getElementById('clear-session').click()),link('Account','#account'),link('Why this exercise? Science & sources','#breathe'));
  }
  return {home,progress,help,account};
}
