// Shared deterministic workflow. Model output never chooses or mutates these transitions.
export const STATES = ['WORRY_CAPTURE','PREDICTION_CLARIFICATION','ACTIONABILITY','PRACTICAL_PROBLEM','INITIAL_RATINGS','CORE_FEARED_MEANING','EVIDENCE_FOR','EVIDENCE_AGAINST','PERSONAL_HISTORY','CALIBRATION','WORST_CASE','COPING','REALISTIC_SCENARIO','REVISED_RATINGS','OUTCOME_PLAN','SUMMARY','COMPLETE'];
const step = (state, field, question, type='text', choices=null) => ({state,field,question,type,choices});
export function steps(s) {
  const a=s.answers;
  const result=[step('WORRY_CAPTURE','worry',"What's worrying you right now?"),step('PREDICTION_CLARIFICATION','prediction','What exactly are you afraid will happen?'),step('ACTIONABILITY','actionability','Is there something you could realistically do about this situation now?','choice',['Something I can act on','An uncertain prediction','Both'])];
  if(a.actionability !== 'An uncertain prediction') result.push(...[
    ['control','What part is within your control?'],['goal','What outcome are you trying to work toward?'],['possibleActions','What are a few possible actions?'],['chosenAction','Which action seems realistic?'],['nextStep','What is one small next step?'],['actionWhen','When might you do it?']
  ].map(([f,q])=>step('PRACTICAL_PROBLEM',f,q)));
  if(a.actionability === 'Something I can act on') result.push(step('PRACTICAL_PROBLEM','exploreRemaining','Would you like to look at an uncertain part of this worry too?','choice',['Save my action plan','Explore the uncertain part']));
  if(a.actionability!=='Something I can act on'||a.exploreRemaining==='Explore the uncertain part') {
    result.push(step('INITIAL_RATINGS','initialProbability','What chance do you currently give your prediction?','rating'),step('INITIAL_RATINGS','initialDistress','How upsetting does the prediction feel right now?','rating'),step('CORE_FEARED_MEANING','coreFearedOutcome','If that happened, what would be the hardest part?'),step('EVIDENCE_FOR','evidenceFor','What makes that outcome seem likely?'),step('EVIDENCE_AGAINST','evidenceAgainst','What points toward things going differently? It is okay if nothing comes to mind.'));
    if(s.relatedIds.length) result.push(step('PERSONAL_HISTORY','personalHistory','Looking at the records you selected, what happened those times?'),step('CALIBRATION','calibrationReflection','What do you make of this pattern?'));
    result.push(step('WORST_CASE','initialSeverity','If it happened, how severe do you imagine it would be?','rating'),step('WORST_CASE','whatNext','What do you think would happen next?'),step('COPING','coping','What could you realistically do, or who could help, if it happened?'),step('COPING','copingConfidence','How confident are you that you could cope if it happened?','rating'),step('REALISTIC_SCENARIO','realisticScenario','What seems like the most realistic version of what might happen?'),step('REVISED_RATINGS','revisedProbability','What chance would you give your original prediction now?','rating'),step('REVISED_RATINGS','revisedSeverity','How severe would it feel now if it happened?','rating'),step('REVISED_RATINGS','revisedDistress','How upsetting does the worry feel now? (optional)','rating'),step('OUTCOME_PLAN','testable','Will you be able to observe whether this prediction happened?','choice',['Yes','No / not sure']));
    if(a.testable==='Yes') result.push(step('OUTCOME_PLAN','outcomeReviewAt','When will you probably know what happened? A date or approximate period is fine.'));
  }
  result.push(step('SUMMARY','approval','Review your words.', 'summary')); return result;
}
export function newWorry(){const now=new Date().toISOString();return {schemaVersion:1,id:crypto.randomUUID(),createdAt:now,updatedAt:now,completedAt:null,status:'draft',cursor:0,answers:{},draftText:'',voice:[],relatedIds:[],outcome:null,revision:0,aiConsent:false,safetyPaused:false};}
export const currentStep=s=>steps(s)[Math.min(s.cursor,steps(s).length-1)];
export function answer(s,value){const next=structuredClone(s),q=currentStep(next);if(q.type==='summary')throw Error('Review first');if(q.type==='rating'){if(value!==null&&(!Number.isInteger(value)||value<0||value>100))throw Error('Choose a number from 0 to 100');}else {if(typeof value!=='string'||value.length>6000)throw Error('Answer is too long');if(q.choices&&!q.choices.includes(value))throw Error('Choose an available option');} next.answers[q.field]=value;next.cursor=Math.min(next.cursor+1,steps(next).length-1);next.draftText='';next.updatedAt=new Date().toISOString();return next;}
export function calibration(records){const resolved=records.filter(r=>r.answers?.testable==='Yes'&&['Happened','Did not happen','Partly happened'].includes(r.outcome?.result));const binary=resolved.filter(r=>r.outcome.result!=='Partly happened'&&Number.isFinite(r.answers.initialProbability));return {resolved,binary,showAggregate:binary.length>=5,showGraph:binary.length>=10,predicted:binary.length?binary.reduce((n,r)=>n+r.answers.initialProbability,0)/binary.length:null,happened:binary.filter(r=>r.outcome.result==='Happened').length};}
export function repeatedWorry(records,text){const normal=t=>String(t).toLowerCase().replace(/[^\p{L}\p{N} ]/gu,'').replace(/\s+/g,' ').trim();const n=normal(text);return n.length>8?records.find(r=>normal(r.answers.worry)===n&&Date.now()-Date.parse(r.updatedAt)<7*86400000):null;}
export function clinicianSummary(s){return {label:'Patient-approved self-report · not a diagnosis',worry:s.answers.worry,prediction:s.answers.prediction,initialProbability:s.answers.initialProbability,revisedProbability:s.answers.revisedProbability,initialSeverity:s.answers.initialSeverity,revisedSeverity:s.answers.revisedSeverity,initialDistress:s.answers.initialDistress,revisedDistress:s.answers.revisedDistress,copingConfidence:s.answers.copingConfidence,evidenceFor:s.answers.evidenceFor,evidenceAgainst:s.answers.evidenceAgainst,coping:s.answers.coping,realisticScenario:s.answers.realisticScenario,nextStep:s.answers.nextStep,actionWhen:s.answers.actionWhen,outcomeReviewAt:s.answers.outcomeReviewAt,outcome:s.outcome,completedAt:s.completedAt};}
