import {currentStep,steps,calibration,repeatedWorry} from './worry-model.js';
import {mountVoice} from './voice.js';
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const button=(text,fn,cls='')=>{const b=el('button',text,cls);b.type='button';b.onclick=fn;return b;};
async function api(path,body){const r=await fetch('/api/'+path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});let d;try{d=await r.json();}catch{throw Error('Saved worry sessions are unavailable. Please keep your current answers on screen.');}if(!r.ok)throw Error(d.error||'Could not save');return d;}
export function createWorry(openSafety){
  const root=document.getElementById('worry-screen');let session,records=[],cleanup=()=>{},queue=Promise.resolve(),saveTimer,dirty=false,draftGeneration=0,active=true,uiToken=0,statusNode,aiReady=false;
  function status(text){if(statusNode?.isConnected)statusNode.textContent=text;}
  function page(title,subtitle){cleanup();cleanup=()=>{};uiToken++;root.replaceChildren();const top=el('div',undefined,'checkin-top');top.append(el('span','WORK THROUGH A WORRY','eyebrow'),button('My worries',()=>home(),'text-button'));const h=el('h1',title);h.tabIndex=-1;statusNode=el('p','', 'save-status');statusNode.setAttribute('role','status');root.append(top,h,el('p',subtitle,'subtle'),statusNode);h.focus();window.scrollTo({top:0,behavior:'instant'});}
  function footer(){const note=el('p','Research preview · Scripts need clinician review, especially for teens. This is not monitored or a substitute for care.','privacy-note');root.append(button('I need safety support',openSafety,'text-button'),note);const evidence=el('details');evidence.append(el('summary','How this works · sources & limits'));const p=el('p','This combines self-monitoring, practical problem solving and thought-record ideas. The combined app and its AI wording have not been clinically validated. Version 1 · reviewed September 30, 2026 · clinical reviewer pending.');evidence.append(p);for(const [label,url] of [['NHS thought records','https://www.nhs.uk/every-mind-matters/mental-wellbeing-tips/self-help-cbt-techniques/thought-record/'],['CCI worry and problem-solving resources','https://www.cci.health.wa.gov.au/Resources/Looking-After-Yourself/Worry-and-Rumination']]){const a=el('a',label);a.href=url;a.target='_blank';a.rel='noopener noreferrer';evidence.append(a,el('br'));}root.append(evidence);}
  async function mutate(op,body={}){const generation=draftGeneration;const id=session.id;const run=queue.catch(()=>{}).then(async()=>{if(session.id!==id)throw Error('Please return to the unfinished session.');const result=await api(`worries/${id}/${op}`,{...body,revision:session.revision});const latest=session.draftText;session=result.session||result;if(draftGeneration===generation)dirty=false;else session.draftText=latest;status(dirty?'Saving…':'Saved to your private account.');return result;});queue=run;return run;}
  async function flush(){clearTimeout(saveTimer);await queue.catch(()=>{});if(dirty)await mutate('draft',{text:session.draftText});}
  function autosave(text){session.draftText=text;draftGeneration++;dirty=true;status('Saving…');clearTimeout(saveTimer);saveTimer=setTimeout(()=>mutate('draft',{text}).catch(e=>status(e.message)),350);}
  function safety(message){page('Let’s pause here.',message||'This concern may need human support. Probability questions are paused.');root.append(button('Open safety support',openSafety,'primary'),el('p','Paasaa has not contacted anyone. If danger is immediate, contact your local emergency service.'));footer();}
  async function home(){active=true;try{await flush();}catch(e){status(e.message);return;}page('A little space for one worry.','Look at one worry more closely — one step at a time.');try{const [r,cap]=await Promise.all([api('worries'),api('status')]);records=r.records;aiReady=cap.ai;root.append(el('p','Your words autosave to your private signed-in account. No clinician receives them automatically. Use synthetic examples while this preview is being reviewed.','privacy-note'));root.append(button('Start a worry',async()=>{try{session=await api('worries',{});render();}catch(e){status(e.message);}},'primary'));
      for(const r of records){const card=el('article',undefined,'worry-card');card.append(el('h2',r.answers.worry||'An unfinished worry'),el('p',r.safetyPaused?'Paused for safety support':r.status==='complete'?'Saved reflection':'In progress'));card.append(button(r.status==='complete'?'View reflection':'Resume',()=>{session=r;r.safetyPaused?safety():render();}));if(r.status==='complete'&&r.answers.testable==='Yes')card.append(button(r.outcome?'Review outcome':'What actually happened?',()=>{session=r;outcome();}));if(r.answers.outcomeReviewAt)card.append(el('p',`Outcome check: ${r.answers.outcomeReviewAt}. No notification is scheduled.`,'subtle'));root.append(card);}footer();
    }catch(e){status(e.message);root.append(button('Try again',home));footer();}}
  function showHistory(){const relevant=records.filter(r=>session.relatedIds.includes(r.id)),c=calibration(relevant);const box=el('div',undefined,'worry-card');box.append(el('h2','Prediction vs reality'));if(!c.resolved.length)box.append(el('p','No resolved outcomes in the records you selected.'));
    for(const r of c.resolved)box.append(el('p',`${r.answers.prediction||r.answers.worry} · predicted ${r.answers.initialProbability??'unanswered'}% · ${r.outcome.result}`));
    if(c.showAggregate)box.append(el('p',`${c.binary.length} selected resolved yes/no predictions: average estimate ${Math.round(c.predicted)}%. Happened in ${c.happened} of ${c.binary.length}. Partial and unclear outcomes are excluded from this comparison.`));else box.append(el('p','Fewer than five comparable yes/no outcomes: individual records only.'));
    if(c.showGraph){const graph=el('div',undefined,'calibration-plot');graph.setAttribute('role','img');graph.setAttribute('aria-label','Predicted likelihood from zero to one hundred percent; observed outcome happened or did not happen. Each dot is one selected record.');graph.append(el('span','Happened', 'plot-top'),el('span','Did not happen','plot-bottom'));for(const r of c.binary){const dot=el('span','●','plot-dot');dot.style.left=`${r.answers.initialProbability}%`;dot.style.top=r.outcome.result==='Happened'?'10%':'65%';dot.title=`${r.answers.initialProbability}%: ${r.outcome.result}`;graph.append(dot);}box.append(graph,el('p','0% — Predicted likelihood — 100%'));}root.append(box);}
  function related(){const eligible=records.filter(r=>r.id!==session.id&&r.status==='complete');if(!eligible.length)return;const details=el('details');details.append(el('summary','Choose earlier records that are relevant (optional)'));for(const r of eligible){const l=el('label',r.answers.prediction||r.answers.worry);const c=el('input');c.type='checkbox';c.checked=session.relatedIds.includes(r.id);c.onchange=async()=>{const ids=c.checked?[...session.relatedIds,r.id]:session.relatedIds.filter(id=>id!==r.id);try{await mutate('related',{ids});}catch(e){status(e.message);}};l.prepend(c);details.append(l);}root.append(details);}
  async function render(){if(!session)return;if(session.safetyPaused){safety();return;}const q=currentStep(session);if(q.type==='summary'||session.status==='complete'){summary();return;}page(q.question,q.type==='rating'?'Your estimate can go up, down, or stay the same. Unanswered is okay.':'One question at a time. You can edit your words or leave a question unanswered.');const token=uiToken;
    const progress=el('p',`${q.state.replaceAll('_',' ').toLowerCase()} · ${session.aiConsent&&aiReady?'AI wording enabled':'guided questions'}`,'eyebrow');root.append(progress);
    if(q.field==='prediction'){root.append(el('blockquote',session.answers.worry));related();}
    if(q.state==='CALIBRATION'||q.state==='PERSONAL_HISTORY')showHistory();
    if(q.field==='realisticScenario')root.append(el('p','You may include what could go wrong, what could go okay, and what you could do if something difficult happens.'));
    let value=session.draftText||(session.answers[q.field]??''),voice=null,input;
    const form=el('form');const label=el('label','Your response');
    if(q.type==='choice'){input=el('select');input.append(new Option('Choose an option',''));for(const c of q.choices)input.append(new Option(c,c));input.value=value;}
    else if(q.type==='rating'){input=el('input');input.type='number';input.min=0;input.max=100;input.step=1;input.value=value===null?'':value;input.placeholder='Unanswered';label.textContent=q.field.includes('Probability')?'Likelihood · 0–100%':'Your rating · 0–100';root.append(el('p',q.field.includes('Probability')?"0% · definitely won't happen — 100% · definitely will happen":'0 · not at all — 100 · extremely / completely','subtle'));}
    else{input=el('textarea');input.rows=4;input.maxLength=6000;input.value=value;}
    input.oninput=()=>{value=input.value;autosave(String(value));};label.append(input);form.append(label);root.append(form);
    if(q.type==='text'){const voiceRoot=el('div',undefined,'voice');form.append(voiceRoot);cleanup=mountVoice(voiceRoot,(text,meta)=>{input.value=text;value=text;voice=meta;autosave(text);},{target:input,available:aiReady});}
    const actions=el('div',undefined,'actions');const next=button(q.field==='prediction'?'Yes, this is what I mean':'Continue',()=>{},'primary');next.type='submit';actions.append(next,button('Back',async()=>{try{await flush();await mutate('back');render();}catch(e){status(e.message);}}));form.append(actions);
    form.onsubmit=async event=>{event.preventDefault();if(!form.reportValidity())return;if(q.type==='choice'&&!value){status('Choose an option.');return;}next.disabled=true;try{await flush();if(q.field==='worry'){const repeated=repeatedWorry(records.filter(r=>r.id!==session.id),String(value));if(repeated&&!form.dataset.checked){form.dataset.checked='true';const notice=el('div',undefined,'worry-card');notice.append(el('p','We worked through this wording recently. Would you like to return to that plan or continue with what has changed?'),button('Return to the earlier plan',()=>{session=repeated;render();}),button('Continue with new information',()=>form.requestSubmit()));form.append(notice);next.disabled=false;return;}}
      const result=await mutate('answer',{value:q.type==='rating'?(value===''?null:Number(value)):String(value),voice:voice?{...voice,patientApprovedText:String(value)}:null});if(result.safety)safety(result.message);else render();}catch(e){status(e.message);next.disabled=false;}};
    const consent=el('label','Use AI to phrase questions using my answers (optional)');const toggle=el('input');toggle.type='checkbox';toggle.checked=session.aiConsent;toggle.disabled=!aiReady;toggle.onchange=async()=>{try{await flush();await mutate('consent',{enabled:toggle.checked});render();}catch(e){status(e.message);}};consent.prepend(toggle);root.append(consent,el('p',aiReady?'When enabled, approved context is sent through our server to Groq. No clinician is notified.':'AI and speech-to-text are not connected yet. Guided typing and saving work without them.','subtle'));footer();
    if(session.aiConsent&&aiReady&&q.type==='text'){try{const result=await api(`worries/${session.id}/question`,{});if(token!==uiToken||!active)return;if(result.safety){safety(result.message);return;}root.querySelector('h1').textContent=result.assistantMessage;if(q.field==='prediction'&&result.extractedData.proposal){const p=el('div',undefined,'worry-card');p.append(el('p','AI suggestion — is this what you mean?'),el('blockquote',result.extractedData.proposal),button('Use this draft and review',()=>{input.value=result.extractedData.proposal;value=input.value;autosave(value);input.focus();}));form.prepend(p);}}catch(e){if(token===uiToken)status('AI wording is unavailable. The standard question remains; your answer is kept.');}}
  }
  function summary(){page('Your words, together.','Review anything before saving. Lower ratings are not the goal.');for(const q of steps(session)){if(!(q.field in session.answers))continue;const card=el('article',undefined,'worry-card');card.append(el('h2',q.field.replace(/([A-Z])/g,' $1')),el('p',session.answers[q.field]===null?'Unanswered':String(session.answers[q.field])),button('Edit',async()=>{try{await mutate('back',{cursor:steps(session).findIndex(x=>x.field===q.field)});render();}catch(e){status(e.message);}}));root.append(card);}if(session.status!=='complete')root.append(button('Save reviewed reflection',async()=>{try{await mutate('complete');summary();status('Your reviewed reflection is saved.');}catch(e){status(e.message);}},'primary'));
    else{root.append(el('p','Saved. Your conclusion and both estimates are kept.'));if(session.answers.testable==='Yes')root.append(button('Record what happened',outcome));root.append(button('View structured clinician summary',async()=>{try{const data=await api(`worries/${session.id}/summary`);const detail=el('section',undefined,'worry-card');detail.append(el('h2','Clinician summary · preview only'),el('p','Not sent to anyone. Patient-approved self-report, not a diagnosis.'));const dl=el('dl');for(const [k,v]of Object.entries(data))if(v!==undefined&&v!==null){dl.append(el('dt',k.replace(/([A-Z])/g,' $1')),el('dd',typeof v==='object'?JSON.stringify(v):String(v)));}detail.append(dl);root.append(detail);}catch(e){status(e.message);}}));}footer();}
  function outcome(){page('What actually happened?','You do not need to make the outcome fit your earlier prediction.');const form=el('form');const fields={};for(const [name,title,type]of [['result','The outcome','select'],['actualSeverity','If it partly happened or happened, how severe was it? (0–100, optional)','number'],['actualCoping','How well were you able to cope? (0–100, optional)','number'],['learning','What did you learn? (optional)','text']]){const l=el('label',title),i=el(type==='select'?'select':type==='text'?'textarea':'input');if(type==='select')for(const v of ['Still unclear','Did not happen','Partly happened','Happened'])i.append(new Option(v,v));if(type==='number'){i.type='number';i.min=0;i.max=100;i.step=1;}if(type==='text')i.maxLength=6000;i.value=(session.outcomeDraft||session.outcome)?.[name]??(type==='select'?'Still unclear':'');fields[name]=i;l.append(i);form.append(l);}const outcomeValues=()=>({result:fields.result.value,actualSeverity:fields.actualSeverity.value===''?null:Number(fields.actualSeverity.value),actualCoping:fields.actualCoping.value===''?null:Number(fields.actualCoping.value),learning:fields.learning.value}); for(const field of Object.values(fields))field.addEventListener('change',()=>{if(form.reportValidity())mutate('outcome-draft',{draft:outcomeValues()}).catch(e=>status(e.message));}); const save=button('Save outcome',()=>{},'primary');save.type='submit';form.append(save);form.onsubmit=async e=>{e.preventDefault();save.disabled=true;try{await mutate('outcome',{result:fields.result.value,actualSeverity:fields.actualSeverity.value===''?null:Number(fields.actualSeverity.value),actualCoping:fields.actualCoping.value===''?null:Number(fields.actualCoping.value),learning:fields.learning.value});summary();}catch(error){status(error.message);save.disabled=false;}};root.append(form);footer();}
  window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
  return {home,leave(){active=false;uiToken++;cleanup();flush().catch(()=>{});}};
}

